### PR TITLE
Adds new kernel hardening checkers and a comment section to the Kernel Config Analyzer

### PR DESCRIPTION
**Pull request by hammadahmedirdeto**
This adds new kernel hardening checkers and a comment section to the Kernel Config Analyzer (KCA) plugin.

The Kernel Config Analyzer (KCA) plugin in the Intel Static Analyzer Framework (ISAFW) does not provide any justification for its kernel configuration recommendations. A comment section has been added to the report. Hardening checkers from Irdeto's Kernel Hardening Guide have been added, increasing hardening checker coverage by 100%. 

Based on pull request 71.
https://github.com/01org/meta-security-isafw/pull/71

Related discussion:
- https://lists.linuxfoundation.org/pipermail/automotive-discussions/2016-August/002438.html
- https://lists.linuxfoundation.org/pipermail/automotive-discussions/2016-May/001981.html
- https://jira.automotivelinux.org/browse/SPEC-118

### CODE REVIEW

**Comment by ereshetova** [comment]
Thank you very much again! But I bet this needs to be rebased also on top of master because of CI

test this please

**Comment by hammadahmedirdeto** [comment]
Will submit this for master as well.

**Comment by ereshetova** [comment]
test this please

**Comment by hammadahmedirdeto** [comment]
Thanks! Do I need to submit a new pull request for jethro?

**Comment by ereshetova** [comment]
Do you need this in Jethro? We haven't used it at all really, so Jethro is not really up to date even. If you need, let me know, I will sync it first and then move all updated commits including this one.

**Comment by hammadahmedirdeto** [comment]
AGL is currently using meta-security-isafw jethro in one of the branches. I would really like to see it jethro. If you need help, please let me know.

**Comment by ereshetova** [comment]
I have synced up jethro with master. There hasn't been any differences in jethro, so it is simple bump to the latest code. Let me know if you have any issues specifically with jethro.

**Comment by hammadahmedirdeto** [comment]
Great Thanks a lot. I will test it with AGL.

**Pull request merged**
