### PR TITLE
layer: Enable isafw class by default when layer is used

### PR DESCRIPTION
**Pull request by serhepopovych**
Enable isafw bitbake class by default when layer is used with BBLAYERS.

Having two step isafw activation looks confusing (especially for those who don't like to read documentation at all). To overcome this I propose to activate isafw class implicitly in layer configuration
conf/layer.conf as some other layers do when they used (e.g. meta-clang).

Thanks.

### CODE REVIEW

**Comment by serhepopovych** [comment]
Also add explicit runtime dependency on binutils for readelf utility to checksec.sh package.

**Comment by ereshetova** [comment]
Sorry for a big delay, we had whole family down with a swine flu that goes around Finland now :( 
I won't be able to take the layer change, since this is what I was explicitly explained in the begging should not be done in Yocto. I was told that when you add a layer into your Yocto build, nothing by default should change, so if someone wants to use isafw, they need to enable it manually like now from their build conf. 

This discussion was a while ago and I don't fully remember the reasons behind. Let me ask to refresh my memory.

**Comment by ereshetova** [comment]
@kad, do you remember the reason why Yocto layers should not enable any functionality by default?

**Comment by kad** [comment]
@ereshetova no, unfortunately I don't remember. might be @rossburton can point to some right place in docs.

**Comment by kad** [comment]
binutils dependency IMHO good catch.

**Comment by serhepopovych** [comment]
@ereshetova delay isn't concern here, hope you and your family will cure completely very soon :-). We have same flu variant dominant in Ukraine too.

Good, I understand that this is a **meta-security-isafw** layer policy for now: not touching everything, except enabled manually. From my point of view however there is no harm with anything in enabling ISAFW by default since this is transparent analysis, and only thing it does (or should do) is to analyse packages/targets/image and produce reports in the build/log/*. On the other hand - we have buildhistory.bbclass from OE-core, that is used in the similar to the current isafw.bbclass (i.e. inheriting it via INHERIT += "isafw"). So just leave anything as is.

I will send new pull request, or just pick commit a0f83ba (checksec: Add explicit runtime dependency on binutils) from this one.

Thanks.

**Comment by ereshetova** [comment]
Ok, no need to send a separate pull request. I will cherry pick the https://github.com/01org/meta-security-isafw/commit/a0f83baad5ce02c99a9ad5749bcd8e554e49a5a7 commit. Thank you!

**Comment by serhepopovych** [comment]
Ok, thank you!

**Comment by ereshetova** [comment]
Commit a0f83baad5ce02c99a9ad5749bcd8e554e49a5a7 is in master now. I am closing this pull request. Thank you!

**Pull request closed without merging**
