### PR TITLE
Python3 compatibility

### PR DESCRIPTION
**Pull request by pohly**
https://github.com/ostroproject/ostro-os/pull/116 now fails in the
isafw classes. These changes should still be compatible with Python2,
but I haven't tested that (will be covered by CI).

### CODE REVIEW

**Comment by pohly** [comment]
retest this please

Only Edison failed (https://ostroproject.org/jenkins/job/dsl-meta-security-isafw_pull-requests/67/) and I've been unable to reproduce locally.

**Comment by pohly** [comment]
And now the code ran fine.

@ereshetova looks like a random failure. Perhaps adding some explicit error reporting around the code which failed will help the next time it occurs. In the meantime, let's merge this PR if you agree.

**Comment by ereshetova** [comment]
I am going to check in more details tomorrow on this. My local runs pass but I cannot see any cfa or fsa reports anymore and I have to debug what is going on. I have separate tests I can run directly on plugins without any bitbake, so I am going to use that for testing.

**Comment by ereshetova** [comment]
other issues fixed in master now, will fire a retest

**Comment by ereshetova** [comment]
retest this please

**Comment by ereshetova** [comment]
retest this please

**Comment by ereshetova** [comment]
this needs rebasing, I pulled all the commits to another PR https://github.com/01org/meta-security-isafw/pull/57  and rebased. Will close this one now.

**Pull request closed without merging**
