### PR TITLE
Next3

### PR DESCRIPTION
**Pull request by serhepopovych**
Hi, again. This is my continued v2 patch series. I would like to merge following changes into upstream:
- Process reports in one shot as last stage of **do_analyse_sources** and *_do_analyse_sources_all_ tasks, as well as default task (e.g. bitbake core-image-minimal) (commit 18aba3a).
- Enable HTML reports in ISA_cve_plugin.py with additional cve-check-tool call. Now we have faux data file prepared by the **do_analysesource** internal task and we can call cve-check-tool multiple times to get required report types. Now we support CSV and HTML reports (commit 17fdb8b).
- Exclude more package classes from the **do_analysesource**. We already exclude _native_ and _cross_, add _nativesdk_, _crosssdk_, _cross-canadian_, _packagegroup_ and _image_ classes (commit dfa2597).

I've made tests against YOCTO jethro branch. Following tests are passed.

bitbake -c analyse_sources openssl
bitbake -c analyse_sources_all core-image-minimal
bitbake core-image-minimal (on already build image, nostamp isn't used in new patches).

Please test.

### CODE REVIEW

**Comment by serhepopovych** [comment]
Unfortunately there is still issues with

bitbake core-image-minimal

when building image from scratch (it just won'ts build).

I'll continue to investigate it.

**Comment by ereshetova** [comment]
Yes, I made tests now and ended up with the same result. do_rootfs is not called and image is not build even if you wipe the whole tmp dir

**Comment by serhepopovych** [comment]
Could you retry tests with following patch (commit 2018667)?

I see no problem with image/target build for now on both YOCTO fido and jethro branches. Also I retried all tests from original pull request description.

Hint: to use _meta-security-isafw_ on fido branch at least two following commits are need to be cherry picked from master branch in _openembedded-core_:
- Commit e11de17 json-glib: enable native builds
- Commit 1405253 json-glib: inherit gnomebase instead of gnome

And bitbake of 1.26 version should be used.

**Comment by ereshetova** [comment]
Seems working for me fine now. Hope I didn't miss anything. I am merging this now. Thank you!

**Comment by ereshetova** [comment]
Actually there is one issue that showed up now and I am debugging this. If you build an image like:

bitbake my_image:do_build

then process_reports task is not called at all. Probably smth related to default tasks...

**Comment by serhepopovych** [comment]
Interesting...

Probably adding something like

``` python
do_build[postfuncs] = "do_process_reports"
```

in the similar way as done for **do_analyse_source** and **do_analyse_sources_all** would solve this problem for

``` shell
bitbake my_image:do_build
```

**do_build** task execution. But for other builds of my_image:do_<task>, where <task> is something other than do_build this of course will not work.

I will look at this problem closely. Thanks for report.

**Comment by ereshetova** [comment]
I brought the issue to Yocto architect yesterday, even he was actually surprised with this behavior, so I am still waiting on his investigation on this.

**Comment by ereshetova** [comment]
Actually do_build[postfuncs] = "do_process_reports" doesn't help and some other ways that I tried. It seems smth is really not right when you do bitbake my_image:do_build...

**Comment by ereshetova** [comment]
Ok, now I have been explained what is going on. So, when you specify smth like:

bitbake my_image:do_xyz

it would execute do_xyz task and all its dependencies, but it won't execute anything after that task. So, if we have our process_report that is specified to run after do_build, it won't be run since we asked bitbake to execute do_build and no further. When you run it normally bitbake my_image, it would execute all tasks. 

So, the suggestion I got for running our task is really to use event handler (bb.event.BuildCompleted). I am going to try it now and see if it works for all the cases. I will post a pull request for testing if it looks ok on my side.

**Pull request merged**
