### PR TITLE
Next

### PR DESCRIPTION
**Pull request by serhepopovych**
Hi. I would like to introduce following changes into upstream project.

Below you can find short description of the introduced changes:
- Enable build with bitbake 1.26. This will enable meta-security-isafw layer usage on fido branch (commit d83614d).
- Cosmetics change: make all lines end with LF instead of CR+LF. Rest of the files in the project uses LF as EOL (commit bf44af4).
- Remove code duplication in isafw.bbclass by abstracting out ISA object initialization (commit bf44af4).
- Adjust logging message formats for certain plugins (commit dc77c00).
- Fix proxy-less configuration environments by not adding http{,s}_proxy environment variables when calling cve-check-tool if self.proxy is set to None (which is considered as valid DNS name and used by libcurl as address of the HTTP(S) proxy).

### CODE REVIEW

**Comment by ereshetova** [comment]
Thank you Sergei for the patches! I just got back from holidays today, but I will look at this tomorrow and test to make sure it works on our side.

**Comment by serhepopovych** [comment]
Next four commits adds following functionality/fixes:
- Introduce new method _->process_report()_ in ISAFW, called at the last (hopefully) stage of the image processing via IMAGE_POSTPROCESS_COMMAND list. This method intended to be used by the ISA_CVE_plugin.py for now to call cve-check-tool only once at the end of image processing (where as _->process_package()_ method being called from _do_analyse_sources_ task to form _.faux file to be used by *->process_report()_ method). Change also addresses concurrency issues by calling only one instance of the cve-checktool (commit a483b83).
- Now after previous commit we have *.faux file with image packages information and can request cve-check-tool to generate various report types. In this case we add HTML report in addition to the CSV (note that cve-check-tool should have proper support for HTML report generation to the stdout added in the cve-check-tool master branch) (commit acda2a3).
- Fix issue introduced by the upstream commit bb8ca16, where we use non-anonymous SSH protocol as GIT repository transport. Use anonymous HTTPS to fix builds in setups without SSH credentials (e.g. public keys).
- Fetch cve-check-tool from git repository master branch. While version 5.5 adds initial support to
  solve concurrency issues (used in _meta-security-isafw_ commit bb8ca16) there is still couple of places related to the concurrency and check results consistency not in 5.5 version (e.g. database can get updated while used by another instances for CVE checks).

Tested with _openembedded-core_ and _meta-security-isafw_ layers only on YOCTO fido branch. Seems work as expected.

Any comments and suggestions as always welcome.

Please review and possibly merge.

Thanks.

**Comment by serhepopovych** [comment]
Following changes are split in two patches:
- First one excludes _nativesdk_, _crosssdk_, _cross-canadian_, _packagegroup_ and image from **do_analyse_sources** task processing in addition to already excluded _native_ and _cross_ (commit 26bc42b).
- Second is to address regression, introduced with commit  a483b83, where user visible tasks **do_analyse_sources** and **do_analyse_sources_all** stop working. Fix by making these user visible
  tasks calling _process_report()_ at the _postfuncs_ stage.

Tested again and found to be working. Also tested on YOCTO jethro branch.

**Comment by ereshetova** [comment]
Thank you for additional fixes! I will restart my test runs now, which haven't even gotten to the task phase yet. It will probably take overnight, since I have not a very fast machine and i need to test on a number of different projects). I will update tomorrow!

**Comment by serhepopovych** [comment]
Well, happy testing!

Waiting for updates. Im perform testing on YOCTO project only for now. Both fido and jethro branches are in my scope.

**Comment by ereshetova** [comment]
Hm, now when I run the basic image build (internal tree) with all the commits, I end up with empty cve report (but faux file has everything correctly). I am too tired to investigate now, I will take a look on this in the morning.

**Comment by ereshetova** [comment]
There is also another issue and that is reproducible at least on OE/jethro builds: if you build an image twice without any changes (bitbake core-image-minimal), then for the second run, do_analyse_source() runs on packages (since it is nostamp), faux file is created correctly, but end cve report is not produced at all. I think the reason is because IMAGE_POSTPROCESS_COMMAND is not invoked since there is no rebuild of rootfs, so it might not be afterall a good idea to do it at this point. You can try changing it to run similar as isafwreport_handler:

isafwreport_handler[eventmask] = "bb.event.BuildStarted"

Just instead specify the event as "bb.event.BuildCompleted"

**Comment by serhepopovych** [comment]
I've prepared possible fix to address issues you described earlier.

Currently tested on YOCTO fido branch only. Probably should work on jethro too.
Seems working. Commit message contains full description of the problem and approach to solve it.

Please try it.

Thanks.

**Comment by ereshetova** [comment]
I don't think marking do_rootfs as nostamp is the correct solution. I am even pretty sure our CI would hang me on a tree right away for doing such a thing :) The idea why package-related processing functions had to be marked nostamp was CVE plugin, which is special in a way that even if package hasn't changed, checks need to be done regulary because new CVEs can just appear in database. However, for all other cases, if input (package, rootfs and etc.) hasn't changed, there should not be a reason to redo the checks and get new report, especially if by doing this we would force a rebuild of rootfs. I think this is quite against Yocto idea.

**Comment by ereshetova** [comment]
I had to do an emergency cve-check-tool recipe upgrade to 5.6 release that just happened minutes ago since we had some issues in CI. Here is the commit: https://github.com/01org/meta-security-isafw/commit/c92cb6e0fec2a0e57fd1563dd04f62d990e66d61

**Comment by serhepopovych** [comment]
Yes, there is a number of issues solved with this version.

I'll probably go with new pull request with hard rebase of my patch series against **analyse_sources** and **analyse_sources_all** task support.

**Comment by serhepopovych** [comment]
Closed now in favour for my v2 series.

**Pull request closed without merging**
