### PR TITLE
Moving process_report to execute as handler and cleaning plugin output

### PR DESCRIPTION
**Pull request by ereshetova**
Currently there is an issue when running "bitbake my_image:do_build" : process_reports task is not executed. Moving the task to be a handler on bb.event.BuildCompleted event. Also, cleaning out the output of all plugins since they spit too much garbage.

### CODE REVIEW

**Comment by ereshetova** [comment]
@popovich-sergei Please try that it doesn't break anything on your side. I tried to push through all kinds of tests and so far worked as expected.

**Comment by serhepopovych** [comment]
It fails in my environment (probably will fail in others) due to missing cve-check-tool in build host system (or toolchain like buildtools-tarball). Thats why I'm not using eventmask at first when you propose to use it.

Tested with **openembedded-core** **master**, probably same results on jethro.

``` shell
which: no cve-check-tool in (<my_PATH_env>)
```

However cve-check-tool was build and native sysroot populated with it.

How about your environment? Do you have cve-check-tool in your PATH variable?

Generally bitbake events seems to be called from bitbake core without any (or minimal) respect to the OE environment. And this seems correct because bitbake is just scheduler and designed to work not only with OE.

**Comment by serhepopovych** [comment]
Even 

``` python
do_build[postfuncs] += "do_process_reports"
```

or

``` python
do_build[prefuncs] += "do_process_reports"
```

does not work.

Very strange.

Probably we should play work task dependencies bit more to fix this issue. say add do_process_reports() somewhere after do_analysesource and before do_build. This would take some time to find solution.

**Comment by ereshetova** [comment]
Actually it seems that it should have worked with respect to accessing cve-check-tool from sysroot from handler function. How does your path looks when executing the handler task? I am not able to try it now on my environment since I am traveling...

**Comment by serhepopovych** [comment]
Well, I'm tested again with _openembedded-core_ at **master** and _meta-security-isafw_ at **devel** branch, and acrually get following response from ISA_cve_plugin.py constructor:

``` shell
...
which: no cve-check-tool in (
/home/sergey/oe/d/openembedded-core/scripts:
/home/sergey/oe/d/bitbake/bin:
/home/sergey/oecore-x86_64/sysroots/x86_64-oesdk-linux/usr/bin:
/home/sergey/bin:
/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin)
...
```

As we can see there is no OE native sysroot, where cve-check-tool-native is installed and should be used in the my PATH environment variable. I only use **buildtools-tarball** on this test machine due to bitbake/oe-core minimal software versions requirements (/home/sergey/oecore-x86_64/sysroots/x86_64-oesdk-linux/usr/bin - PATH entry).

**Comment by serhepopovych** [comment]
Output was produced by the following code, just because _which_ uses stderr to report errors:

``` python
    DEVNULL = open(os.devnull, 'wb')
    rc = subprocess.call(["which", "cve-check-tool"], stdout=DEVNULL)
    DEVNULL.close()
```

**Comment by rpurdie** [comment]
Can you tell us where you placed this code? More context on where you're seeing this error would be helpful, such as the log from the surrounding build.

**Comment by ereshetova** [comment]
@rpurdie cve-check-tool is downloaded inside sysroot by bitbake, since we have this: 

https://github.com/01org/meta-security-isafw/blob/master/classes/isafw.bbclass#L23

What I don't understand is why it isn't find in the case it is called from handler function, but found fine when it is called from the task.

**Comment by rpurdie** [comment]
@ereshetova I'm thinking that no do_analysesource has run in this case yet the build has completed, therefore its being run without the tool being present? If might be you just need to detect/ignore that?

**Comment by ereshetova** [comment]
@rpurdie, in the case when do_analysesource hasn't run, then yes, plugin in init function will complain about tool not being present, but it doesn't fail anything. The actually processing code won't run. @popovich-sergei, my impression was that you have observed cve-check-tool missing when calling from handler, while do_analysesource has run and it was present there. Is this correct?

**Comment by serhepopovych** [comment]
Hi, sorry for long delay. I have remade tests with current **openembedded-core** at _next_ branch with my local fixes to the layer (not upstreamed yet) based on upstream _master_ and **meta-security-isafw** at _devel_ layers only. I'm using RHEL6 as buildhost with buildtools-tarball.

Note that python traces related to the lxml binding happened due to missing python-lxml in buildtools-tarball.

I get following output:

``` shell
[sergey@<bld-host> build-master]$ bitbake core-image-minimal
Parsing recipes: 100% |########################################################################################################################################| ETA:  00:00:00
Parsing of 872 .bb files complete (0 cached, 872 parsed). 1304 targets, 61 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION        = "1.29.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "RedHatEnterpriseServer-6.X"
TARGET_SYS        = "i586-oe-linux"
MACHINE           = "qemux86"
DISTRO            = "nodistro"
DISTRO_VERSION    = "nodistro.0"
TUNE_FEATURES     = "m32 i586"
TARGET_FPU        = ""
meta              = "next:11cea0d5aba98613dd3023a67d45a62329686677"
meta-security-isafw = "devel:cdd0a97bb01f86ee433a0d70c639c639fe63e047"

NOTE: Preparing RunQueue
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
NOTE: Tasks Summary: Attempted 1531 tasks of which 9 didn't need to be rerun and all succeeded.
(<type 'exceptions.ImportError'>, ImportError('No module named lxml',), <traceback object at 0x7f66c5075368>)
(<type 'exceptions.ImportError'>, ImportError('No module named lxml',), <traceback object at 0x7f66cc521638>)
(<type 'exceptions.ImportError'>, ImportError('No module named lxml',), <traceback object at 0x7f66c5075368>)
which: no cve-check-tool in (/home/sergey/oe/d/openembedded-core/scripts:/home/sergey/oe/d/bitbake/bin:/home/sergey/oecore-x86_64/sysroots/x86_64-oesdk-linux/usr/bin:/home/sergey/bin:/bin:/bin:/usr/sbin:/sbin:/usr/bin)
('Exception in plugin: ', (<type 'exceptions.ImportError'>, ImportError('No module named lxml',), <traceback object at 0x7f66cd975710>))
```

As we can note PATH does not contain <native_sysroot>/usr/bin directory, where cve-check-tool resides.

@ereshetova yes, you are correct. this report is from ISA_CVEChecker constructor, called from ISA class constructor, called from isafw.bbclass:isafw_init(), called from isafw.bbclass:process_reports_handler, triggeded by the bitbake as BuildComplete eventmask.

**Comment by ereshetova** [comment]
@rpurdie, I can confirm that I was able to reproduce behaviour after removing from my host cve-check-tool, the handler is not able to find it. So, there is an issue with path variable. Is it possible that path is cleaned before that after build completes?

**Comment by rpurdie** [comment]
@ereshetova You are correct, I really thought PATH was setup in this environment but it seems it is not. Sorry about the confusion. It is however easy to fix, you can either run commands in the form "PATH=%s xxx" % d.getVar("PATH", True) or export PATH into the environment with something like savedenv = os.environ.copy(); os.environ["PATH"] = d.getVar("PATH", True); <commands>; os.environ["PATH"] = savedenv["PATH"].

**Comment by ereshetova** [comment]
@rpurdie, thank you, I will try exporting path, I guess this should work, but I wonder if this is desired behaviour from OE side. Is it really normal that path is setup correctly when tasks are executed, but not when handlers are?

**Comment by ereshetova** [comment]
Ok, here is updated pull request (rebased also). Work for me even with wiped out cve-check-tool from the host. 
@popovich-sergei please test on your side.

**Comment by serhepopovych** [comment]
@ereshetova Passed. Works with _openembedded-core_ **master** and _meta-security-isafw_ **devel** layers as expected on RHEL6 machines.

Thanks.

**Comment by ereshetova** [comment]
Great, merging then!

**Pull request merged**
