### PR TITLE
Added xml report for fsa & kca plugins, changed to UTF-8 encoding

### PR DESCRIPTION
**Pull request by besabasr**

### CODE REVIEW

**Comment by besabasr** [comment]
Thanks for your comments Elena, a couple of questions:
    for 1), do you consider the tag testcase suitable for fsa and kca, or can I change it for section?
    for 3), I am afraid the desired format didn't print here, can you send it via email?

**Comment by besabasr** [comment]
Added some changes will complete with your suggestion especially kca's

**Comment by ereshetova** [comment]
Ups, indeed markdown is a stupid language.Here is what is not displayed: 

value current="CONFIG_ARCH_BINFMT_ELF_RANDOMIZE_PIE:not set"/>
value rcmmndd="CONFIG_ARCH_BINFMT_ELF_RANDOMIZE_PIE:y"/>

would be better to have it as:

value current="CONFIG_ARCH_BINFMT_ELF_RANDOMIZE_PIE:not set" rcmmndd="CONFIG_ARCH_BINFMT_ELF_RANDOMIZE_PIE:y"/>

 for 1), do you consider the tag testcase suitable for fsa and kca, or can I change it for section?
I think we can consider them all to be testcases since we use junit xml format.

**Comment by besabasr** [comment]
Your suggestions were included

**Comment by ereshetova** [comment]
The output looks correct now. I am merging this one. Thank you!

**Pull request merged**
