### PR TITLE
Fixing error on finding cve-check-tool in the new sysroot setup.

### PR DESCRIPTION
**Pull request by ereshetova**
For more details, see
https://github.com/01org/meta-security-isafw/issues/79

### CODE REVIEW

**Comment by mythi** [comment]
@ereshetova I tested this but it fails if I run ```do_analysesource``` for two different recipes.

```bitbake -v -c analysesource systemd```
```bitbake -v -c analysesource libxml2```

With the latter the log file says 'install cve-check-tool'.

The license plugin does not report any errors but I believe that suffers from the same problem. It's a different problem but perhaps it should be blacklisted completely if ```PACKAGE_CLASSES``` does not contain rpm.

**Comment by ereshetova** [comment]
@mythi, I was exactly about to ask how to test this on anything other than OE.
Have you tested it while doing the image build? This is the way I have been testing it. Do you still need to be able to run it per task? If yes, then I would need to investigate it further. However, I think in CI it is run per image, so your main issue should be resolved.

License plugin doesn't need anything external to be installed, but I will check what happens if you run it just via separate task.

**Comment by ereshetova** [comment]
I was too hasty to delete dependency on the tool from do_analysesource. I will need to refactor the plugin in the future a bit more to be able to remove it.

**Comment by mythi** [comment]
@ereshetova +1 verified to satisfy errors reported in #79

**Comment by ereshetova** [comment]
Ok, I am merging this now then and next will do changes to plugin to remove non-mandatory dependencies.

**Pull request merged**
