### PR TITLE
Devel

### PR DESCRIPTION
**Pull request by ereshetova**

### CODE REVIEW

**Comment by pohly** [comment]
In practice, LGPLv3+ and GPLv3+ are also used.

Let's add all variations (with and without hyphen, with and without .0, with and without trailing +).

I'm wondering whether a regular expression for the license check might work better...

**Comment by ereshetova** [comment]
Actually since they get processed to canonical form here: https://github.com/01org/meta-security-isafw/blob/master/classes/isafw.bbclass#L59 they no longer become LGPLv3+ and GPLv3+. This does work currently since I think all GPLv3+ are already reported.

**Comment by pohly** [comment]
@elena: http://ostro.ostc.intel.com/download/builds/meta-security-isafw_pull-requests/48/latest/isafw/intel-corei7-64/la_problems_report_intel-corei7-64_20160519065934 still does not mention gmp at all.

But it is installed, see for example http://ostro.ostc.intel.com/download/builds/meta-security-isafw_pull-requests/48/latest/images/intel-corei7-64/ostro-image-noswupd-intel-corei7-64-2016-05-18_23-42-59-build-33.rootfs.manifest

**Comment by ereshetova** [comment]
@pohly, it is also in my pkg list, I will check tomorrow with debug what is going on

**Comment by ereshetova** [comment]
@pohly, I found the reason for such behaviour. When I obtain info about binary pkg name and its license, I get this for gmp: libgmpxx:LGPL-3.0+ (already translate to canonical form). But then I check if binary pkg present in the imge, that check fails because there is no  libgmpxx, but there is  libgmp10. I believe the reason why I get libgmpxx is here: https://github.com/ostroproject/ostro-os/blob/dfffebdd496fc1b7bf3bb2804ea64b6442095035/meta/recipes-support/gmp/gmp_6.1.0.bb#L24  

I am not sure if such declaration is even correct fully...

**Comment by pohly** [comment]
libgmpxx is the C++ version of the library: tmp-glibc/work/corei7-64-ostro-linux/gmp/6.1.0-r0/packages-split/libgmpxx/usr/lib/libgmpxx.so.4.5.0

libgmp10.so is the C version, and it should be in package "gmp": tmp-glibc/work/corei7-64-ostro-linux/gmp/6.1.0-r0/packages-split/gmp/usr/lib/libgmp.so.10.3.0

However, the actual .ipk are indeed named differently:
tmp-glibc/deploy/ipk/corei7-64/libgmp10_6.1.0-r0_corei7-64.ipk
tmp-glibc/deploy/ipk/corei7-64/libgmp-doc_6.1.0-r0_corei7-64.ipk
tmp-glibc/deploy/ipk/corei7-64/libgmp-dbg_6.1.0-r0_corei7-64.ipk
tmp-glibc/deploy/ipk/corei7-64/libgmpxx4_6.1.0-r0_corei7-64.ipk
tmp-glibc/deploy/ipk/corei7-64/libgmp-dev_6.1.0-r0_corei7-64.ipk

I'm not sure where and how the .ipk package names are chosen. But it seems that when you analyze the set of installed ipk packages in an image, you need to map back to the bitbake package before you can find the corresponding recipe.

I'll try to find out...

**Comment by pohly** [comment]
The actual renaming is done by debian.bbclass, but not only there. Some recipes also use PKG_ variables to do their own renaming, so disabling debian.bblcass would not avoid the issue.

RP pointed out that the sysroot's pkgdata directory can be used to map back:

```
$ ls -l tmp-glibc/sysroots/intel-corei7-64/pkgdata/runtime-reverse/libgmp10 
lrwxrwxrwx 1 pohly pohly 14 May 19 18:54 tmp-glibc/sysroots/intel-corei7-64/pkgdata/runtime-reverse/libgmp10 -> ../runtime/gmp
pohly@pohly-desktop:/fast/build/ostro-gt/intel-corei7-64$ cat tmp-glibc/sysroots/intel-corei7-64/pkgdata/runtime-reverse/libgmp10
PN: gmp
PV: 6.1.0
PR: r0
PKGV: 6.1.0
PKGR: r0
LICENSE: GPLv2+ | LGPLv3+
DESCRIPTION: GMP is a free library for arbitrary precision arithmetic, operating on signed integers, rational numbers, and floating point numbers
SUMMARY: GNU multiprecision arithmetic library
RDEPENDS_gmp: glibc (>= 2.24)
RPROVIDES_gmp:  gmp (=6.1.0)
SECTION: devel
PKG_gmp: libgmp10
FILES_gmp: /usr/bin/* /usr/sbin/* /usr/libexec/* /usr/lib/lib*.so.* /etc /com /var /bin/* /sbin/* /lib/*.so.* /lib/udev/rules.d /usr/lib/udev/rules.d /usr/share/gmp /usr/lib/gmp/* /usr/share/pixmaps /usr/share/applications /usr/share/idl /usr/share/omf /usr/share/sounds /usr/lib/bonobo/servers
pkg_postinst_gmp: #!/bin/sh\nif [ x"$D" = "x" ]; then\n\tif [ -x /sbin/ldconfig ]; then /sbin/ldconfig ; fi\nfi\n
FILERPROVIDESFLIST_gmp: /usr/lib/libgmp.so.10.3.0
FILES_INFO: {"/usr/lib/libgmp.so.10": 16, "/usr/lib/libgmp.so.10.3.0": 485336}
FILERPROVIDES_/usr/lib/libgmp.so.10.3.0_gmp: elf(buildid) (= aba039c8a53c07d82078b57fe9b48384a4f82880) libgmp.so.10()(64bit)
FILERDEPENDSFLIST_gmp: /usr/lib/libgmp.so.10.3.0
FILERDEPENDS_/usr/lib/libgmp.so.10.3.0_gmp: libc.so.6()(64bit) libc.so.6(GLIBC_2.14)(64bit) libc.so.6(GLIBC_2.2.5)(64bit) libc.so.6(GLIBC_2.3)(64bit) libc.so.6(GLIBC_2.3.4)(64bit) libc.so.6(GLIBC_2.4)(64bit) libc.so.6(GLIBC_2.7)(64bit) rtld(GNU_HASH)
PKGSIZE_gmp: 485352
```

**Comment by ereshetova** [comment]
@pohly, this unfortunately would mean changing the whole way how I am processing licenses.. Currently, I create a mapping between binary package name and licenses for this package and then check if violation licenses are present. Then from that list I verify if the package is present in the image or not.

However, now, I would probably need to store in addition the mapping between the source package and its licenses also and then for ones that violate licenses I would need to check if any binary pkg present in the image maps back to this source package...

**Comment by pohly** [comment]
@ereshetova can't you do a mapping from ipkg package name back to "conceptual" package name, at the time when reading the image manifest?

I'm currently wondering about the intended usage of the image manifest files. Perhaps it should get extended to include both actual package name and conceptual name, or, if that is not possible, a second file with those different names should be created.

This reliance on sysroots/*/pkgdata makes it currently impossible to map back to recipe meta data after deploying images and using just the deployed data, because the mapping is not getting deployed.

**Comment by ereshetova** [comment]
@pohly, I will try doing that. I will merge this PR since it does contain needed fix in any case and then try doing the mapping separately.

**Pull request merged**
